export const mockFormData = [
  {
    label: 'Name',
    placeholder: 'Enter your name',
    type: 'text',
    name: 'name',
    value: '',
  },
  {
    label: 'Age',
    placeholder: 'Enter your age',
    type: 'number',
    name: 'age',
    value: '',
  },
  {
    label: 'Email',
    placeholder: 'Enter your email',
    type: 'email',
    name: 'email',
    value: '',
  },
  {
    label: 'Phone',
    placeholder: 'Enter your phone number',
    type: 'tel',
    name: 'phone',
    value: '',
  },
  {
    label: 'Address',
    placeholder: 'Enter your address',
    type: 'text',
    name: 'address',
    value: '',
  },
  {
    label: 'City',
    placeholder: 'Enter your city',
    type: 'text',
    name: 'city',
    value: '',
  },
  {
    label: 'Phone',
    placeholder: 'Enter your phone number',
    type: 'tel',
    name: 'phone',
    value: '',
  },
  {
    label: 'Email',
    placeholder: 'Enter your email',
    type: 'email',
    name: 'email',
    value: '',
  },
  {
    label: 'Email',
    placeholder: 'Enter your email',
    type: 'email',
    name: 'email',
    value: '',
  },
  {
    label: 'City',
    placeholder: 'Enter your city',
    type: 'text',
    name: 'city',
    value: '',
  },
];
